### ISSUE TITLE
Only 1 file downloaded (out of two)

### ISSUE THREAD

**Issue by keehoo** [nickypangers/arb-editor#1]
I've encountered an issue with exporting files, even though two languages were in the project, export button downloaded only one.

**Comment by nickypangers** [comment]
Let me try and recreate. Thanks for letting me know.

**Comment by nickypangers** [comment]
Let me try and recreate. Thanks for letting me know.

**Comment by nickypangers** [comment]
Did you enable download multiple files from your browser? I have tried and it downloads without any problems. Thanks.

**Comment by nickypangers** [comment]
Did you enable download multiple files from your browser? I have tried and it downloads without any problems. Thanks.
